In [2]:
import pandas as pd

In [3]:
df_customers = pd.read_csv(r"files\olist_customers_dataset.csv", dtype={'customer_zip_code_prefix':str})

In [4]:
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [5]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  object
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

In [6]:
df_customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix    object
customer_city               object
customer_state              object
dtype: object

In [7]:
df_customers['customer_zip_code_prefix']

0        14409
1        09790
2        01151
3        08775
4        13056
         ...
99436    03937
99437    06764
99438    60115
99439    92120
99440    06703
Name: customer_zip_code_prefix, Length: 99441, dtype: object

In [8]:
df_customers.describe()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441,99441,99441
unique,99441,96096,14994,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,22790,sao paulo,SP
freq,1,17,142,15540,41746

In [9]:
df_customers.columns = df_customers.columns.astype('str')

In [10]:
df_customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix    object
customer_city               object
customer_state              object
dtype: object

In [11]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\ritee\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\ritee\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ritee\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ritee\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [12]:
# # Connect to postgresql

# from sqlalchemy import create_engine

# username = 'postgres'
# password = 'Student.edu0'
# host = 'localhost'
# port = '5432'
# database = 'olist'

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # load datframe into postgresql

# table_name = 'olist_customers_dataset'
# df_customers.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

In [13]:
df_geolocation = pd.read_csv(r"files\olist_geolocation_dataset.csv",dtype={'geolocation_zip_code_prefix':str})

In [14]:
df_geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545621,-46.639292,sao paulo,SP
1,01046,-23.546081,-46.644820,sao paulo,SP
2,01046,-23.546129,-46.642951,sao paulo,SP
3,01041,-23.544392,-46.639499,sao paulo,SP
4,01035,-23.541578,-46.641607,sao paulo,SP

In [15]:
df_geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  object
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), object(3)
memory usage: 38.2+ MB

In [16]:
df_geolocation.shape

(1000163, 5)

In [17]:
# # Connect to postgresql

# from sqlalchemy import create_engine

# username = 'postgres'
# password = 'Student.edu0'
# host = 'localhost'
# port = '5432'
# database = 'olist'

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # load datframe into postgresql

# table_name = 'olist_geolocation_dataset'
# df_geolocation.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

In [18]:
df_order_items = pd.read_csv(r"files\olist_order_items_dataset.csv")

In [19]:
df_order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [20]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [21]:
# change the shipping_limit_date object to datetime


df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'])

In [22]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [23]:
# Connect to postgresql

# username = 'postgres'
# password = 'Student.edu0'
# host = 'localhost'
# port = '5432'
# database = 'olist'

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # load datframe into postgresql

# table_name = 'olist_order_items_dataset'
# df_order_items.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

In [24]:
df_order_payments = pd.read_csv(r"files\olist_order_payments_dataset.csv")

In [25]:
df_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [26]:
df_order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [27]:
df_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [28]:
# create group of installments


# Assign "No Installment" to 0
df_order_payments.loc[df_order_payments['payment_installments'] == 0, 'installment_group'] = 'No Installment'

bins = [0,2,6,12,24]

labels = ['Short (1-2)', 'Medium (3-6)', 'Long (7-12)', 'Very Long (13-24)']

# Apply pd.cut only to rows > 0
df_order_payments.loc[df_order_payments['payment_installments'] > 0, 'installment_group'] = pd.cut(
    df_order_payments.loc[df_order_payments['payment_installments'] > 0, 'payment_installments'],
    bins=bins,
    labels=labels,
    right=True,
    include_lowest=False  # exclude 0 since we already handled it
)

In [29]:
df_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,installment_group
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,Long (7-12)
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,Short (1-2)
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,Short (1-2)
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,Long (7-12)
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,Short (1-2)

In [30]:
df_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,installment_group
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,Long (7-12)
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,Short (1-2)
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,Short (1-2)
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,Long (7-12)
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,Short (1-2)

In [31]:
# table_name = 'olist_order_payments_dataset'
# df_order_payments.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

In [32]:
df_order_review = pd.read_csv(r'files\olist_order_reviews_dataset.csv')

In [33]:
df_order_review.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [34]:
df_order_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [35]:
df_order_review.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [36]:
df_order_review['review_comment_title'] = df_order_review['review_comment_title'].fillna('No Title')

In [37]:
df_order_review.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title           0
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [38]:
df_order_review['review_comment_message'] = df_order_review['review_comment_message'].fillna('No comment')

In [39]:
df_order_review.isna().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [40]:
df_order_review.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [41]:
df_order_review['review_score']

0        4
1        5
2        5
3        5
4        5
        ..
99219    5
99220    5
99221    5
99222    4
99223    1
Name: review_score, Length: 99224, dtype: int64

In [42]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\ritee\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\ritee\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ritee\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ritee\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [43]:
# Connect to postgresql

from sqlalchemy import create_engine

# username = 'postgres'
# password = 'Student.edu0'
# host = 'localhost'
# port = '5432'
# database = 'olist'

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # load datframe into postgresql

# table_name = 'olist_order_reviews_dataset'
# df_order_review.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

In [44]:
df_order_dataset = pd.read_csv(r'files\olist_orders_dataset.csv')

In [45]:
df_order_dataset.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [46]:
df_order_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [47]:
df_order_dataset.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [48]:
df_order_dataset[['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date']]

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
0,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13
1,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45
2,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29
3,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42
4,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02
...,...,...,...
99436,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01
99437,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56
99438,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17
99439,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54
99440,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30

In [49]:
cancelled_order_count = (df_order_dataset['order_status']=='canceled').sum()
print(cancelled_order_count)

625

In [50]:
df_order_dataset.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [51]:
df_order_dataset.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [53]:
for col in df_order_dataset.columns[3:]:
    df_order_dataset[col] = pd.to_datetime(df_order_dataset[col],errors='coerce')

In [54]:
df_order_dataset.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [ ]:
# from sqlalchemy import create_engine

# username = 'postgres'
# password = 'Student.edu0'
# host = 'localhost'
# port = '5432'
# database = 'olist'

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # load datframe into postgresql

# table_name = 'olist_orders_dataset'
# df_order_dataset.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

data successfully laoded in olist_orders_dataset

In [56]:
df_order_dataset.shape

(99441, 8)

In [57]:
df_products_dataset = pd.read_csv(r'files\olist_products_dataset.csv')

In [58]:
df_products_dataset.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [60]:
df_products_dataset.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [61]:
df_products_dataset.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [62]:
df_products_dataset['product_category_name']

0                               perfumaria
1                                    artes
2                            esporte_lazer
3                                    bebes
4                    utilidades_domesticas
                       ...
32946                     moveis_decoracao
32947    construcao_ferramentas_iluminacao
32948                      cama_mesa_banho
32949               informatica_acessorios
32950                      cama_mesa_banho
Name: product_category_name, Length: 32951, dtype: object

In [63]:
(df_products_dataset.isna().mean() * 100).round(2)

product_id                    0.00
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

In [64]:
df_products_dataset[df_products_dataset['product_category_name'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [65]:
df_products_dataset[df_products_dataset['product_category_name'].isna()].isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [66]:
df_products_dataset['product_weight_g'].describe()

count    32949.000000
mean      2276.472488
std       4282.038731
min          0.000000
25%        300.000000
50%        700.000000
75%       1900.000000
max      40425.000000
Name: product_weight_g, dtype: float64

In [69]:
df_products_dataset[df_products_dataset['product_category_name'].isna()].describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,0.0,0.0,0.0,609.000000,609.000000,609.000000,609.000000
mean,NaN,NaN,NaN,2250.765189,28.719212,15.814450,22.566502
std,NaN,NaN,NaN,4429.016600,14.398293,13.678043,12.087371
min,NaN,NaN,NaN,50.000000,15.000000,2.000000,11.000000
25%,NaN,NaN,NaN,250.000000,16.000000,5.000000,13.000000
50%,NaN,NaN,NaN,700.000000,25.000000,12.000000,20.000000
75%,NaN,NaN,NaN,1683.000000,35.000000,22.000000,30.000000
max,NaN,NaN,NaN,30000.000000,105.000000,92.000000,80.000000

In [71]:
df_products_dataset[df_products_dataset['product_category_name'].notna()].describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32340.000000,32340.000000,32340.000000,32340.000000
mean,48.476949,771.495285,2.188986,2276.956586,30.854545,16.958813,23.208596
std,10.245741,635.115225,1.736766,4279.291845,16.955965,13.636115,12.078762
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [72]:
df_products_dataset['product_category_name'] = df_products_dataset['product_category_name'].fillna('Unknown')

In [73]:
df_products_dataset.isna().sum()

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [74]:
df_products_dataset['product_name_lenght'] = (
    df_products_dataset['product_name_lenght']
    .fillna(len("unknown"))
)

In [75]:
df_products_dataset.isna().sum()

product_id                      0
product_category_name           0
product_name_lenght             0
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [76]:
df_products_dataset.fillna({
    'product_description_lenght': 0,
    'product_photos_qty': 0
}, inplace=True)

In [77]:
df_products_dataset.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              2
product_length_cm             2
product_height_cm             2
product_width_cm              2
dtype: int64

In [78]:
for col in ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    median_val = df_products_dataset[col].median()
    df_products_dataset[col].fillna(median_val, inplace=True)

C:\Users\ritee\AppData\Local\Temp\ipykernel_18668\1991672295.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_products_dataset[col].fillna(median_val, inplace=True)

In [79]:
df_products_dataset.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [ ]:
# username = 'postgres'
# password = 'Student.edu0'
# host = 'localhost'
# port = '5432'
# database = 'olist'

# engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# # load datframe into postgresql

# table_name = 'olist_products_dataset'
# df_products_dataset.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

data successfully laoded in olist_products_dataset

In [84]:
df_sellers_dataset = pd.read_csv(r'files\olist_sellers_dataset.csv',dtype={'seller_zip_code_prefix':str})

In [85]:
df_sellers_dataset.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [86]:
df_sellers_dataset.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [ ]:
# table_name = 'olist_sellers_dataset'
# df_sellers_dataset.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

data successfully laoded in olist_sellers_dataset

In [88]:
df_product_category_translation = pd.read_csv(r'files\product_category_name_translation.csv')

In [89]:
df_product_category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [90]:
df_product_category_translation.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [ ]:
# table_name = 'product_category_translation'
# df_product_category_translation.to_sql(table_name,engine,if_exists="replace",index=False)

# print(f"data successfully laoded in {table_name}")

data successfully laoded in product_category_translation